language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

branches:
  only:
    - master

before_install:
  - brew update
  - brew install ag
  - brew install rg

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
